export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGIN_2FA_VERIFY: '/auth/login/2fa/verify',
    SIGNUP: '/auth/signup',
    LOGOUT: '/auth/logout',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH_TOKEN: '/auth/refresh',
    CURRENT_USER: '/auth/me',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    OAUTH_GOOGLE_AUTHORIZE: '/oauth2/authorize/google',
    OAUTH_GITHUB_AUTHORIZE: '/oauth2/authorize/github',
    OAUTH_EXCHANGE: '/auth/oauth2/exchange',
  },
  RESUMES: {
    LIST: '/resumes',
    GET: (id: number) => `/resumes/${id}`,
    DELETE: (id: number) => `/resumes/${id}`,
    OPTIMIZE: (id: number) => `/resumes/${id}/optimize`,
    UPLOAD: '/resumes/upload',
    ANALYZE: (id: number) => `/resumes/${id}/analyze`,
    OPTIMIZE_UPLOAD: '/resumes/optimize-upload',
    BUILD_FROM_DATA: '/resumes/build/from-data',
    BUILD_PDF: '/resumes/build/pdf',
  },
  COVER_LETTERS: {
    GENERATE: '/cover-letters/generate',
    GENERATE_FROM_FILE: '/cover-letters/generate-from-file',
    LIST: '/cover-letters',
    GET: (id: number) => `/cover-letters/${id}`,
    UPDATE: (id: number) => `/cover-letters/${id}`,
    DELETE: (id: number) => `/cover-letters/${id}`,
    REGENERATE: (id: number) => `/cover-letters/${id}/regenerate`,
  },
  JOBS: {
    LIST: '/jobs',
    CREATE: '/jobs',
    GET: (id: number) => `/jobs/${id}`,
    UPDATE: (id: number) => `/jobs/${id}`,
    DELETE: (id: number) => `/jobs/${id}`,
    BY_STATUS: (status: string) => `/jobs/status/${status}`,
    SEARCH: '/jobs/search',
  },
  DASHBOARD: {
    MAIN: '/dashboard',
    STATS: '/dashboard/stats',
    RECENT_APPLICATIONS: '/dashboard/recent-applications',
    FUNNEL: '/dashboard/funnel',
    METRICS: '/dashboard/metrics',
    SUCCESS_METRICS: '/dashboard/success-metrics',
    APPLICATION_VELOCITY: '/dashboard/application-velocity',
  },
  SETTINGS: {
    PROFILE: '/settings/profile',
    PROFILE_PHOTO: '/settings/profile/photo',
    BILLING: {
      PLAN: '/settings/billing/plan',
      PAYMENT_METHOD: '/settings/billing/payment-method',
      INVOICES: '/settings/billing/invoices',
      CANCEL_SUBSCRIPTION: '/settings/billing/subscription/cancel',
    },
    SECURITY: {
      MAIN: '/settings/security',
      CHANGE_PASSWORD: '/settings/security/password',
      SETUP_2FA: '/settings/security/2fa/setup',
      ENABLE_2FA: '/settings/security/2fa/enable',
      DISABLE_2FA: '/settings/security/2fa/disable',
    },
    ACCOUNT: {
      DELETE: '/settings/account/delete',
      EXPORT: '/settings/account/export',
    },
  },
  ADMIN: {
    USERS: '/admin/users',
    ANALYTICS: '/admin/analytics',
  },
} as const;
